backend = "fastresize"
check_contrast = true
color_space = "lab"
fallback_generator = "complementary"
palette = "ansidark16"

[templates]
foot =								{ src = "foot",								dst = "~/.config/foot/foot.ini" }
nvim =								{ src = "nvim",								dst = "~/.cache/wallust/colors_neopywal.vim" }
niri =								{ src = "niri",								dst = "~/.config/niri/config.kdl" }
swaylock =						{ src = "swaylock",						dst = "~/.config/swaylock/config" }
mako =								{ src = "mako",								dst = "~/.config/mako/config" }
waybar =							{ src = "waybar",							dst = "~/.config/waybar/style.css" }
rofi-applauncher =		{ src = "rofi-applauncher",		dst = "~/.config/rofi/applauncher.rasi" }
rofi-powermenu =			{ src = "rofi-powermenu",			dst = "~/.config/rofi/powermenu.rasi" }
rofi-wallpapermenu =	{ src = "rofi-wallpapermenu",	dst = "~/.config/rofi/wallpapermenu.rasi" }
