#!/usr/bin/fish
set poweroff " Poweroff"
set reboot " Reboot"
set lock " Lock"
set exit "󰗼 Exit"
set sleep "󰒲 Suspend"
set hibernate " Hibernate"

set chosen (echo -e "$poweroff\n$reboot\n$lock\n$exit\n$sleep\n$hibernate" | fuzzel --dmenu --lines 6 --width 15 --prompt "" --placeholder "")

switch $chosen
case $poweroff
  shutdown now
case $reboot
  reboot
case $lock
  loginctl lock-session
case $exit
  niri msg action quit
case $sleep
  systemctl suspend
case $hibernate
  systemctl hibernate
case '*'
  exit 1
end
