#!/usr/bin/fish

if test (count $argv) -lt 1; or not test -f $argv[1]
  echo "Usage: $(status filename) <img>"
  exit 1
end

set -x SWWW_TRANSITION "any"
set -x SWWW_TRANSITION_FPS 60
set -x SWWW_TRANSITION_DURATION 1.5

niri msg action do-screen-transition 
wallust run $argv[1]; and begin
	set -U img $argv[1]
	swww img $argv[1]
	makoctl reload
	notify-send -i $argv[1] "Wallust" "Changed wallpaper and palette."
end; or begin
	notify-send -u critical "Wallust" "Failed to change palette"
end;

