#!/usr/bin/fish

if test (count $argv) -lt 1; or not test -d $argv[1]
  echo "Usage: $(status filename) <dir>"
  exit 1
end

~/.config/scripts/set_background "$(fd -t f -d 1 -E "$IMG" -e jpg -e png -e webp . "$argv[1]" | shuf -n1)"
