#!/usr/bin/fish

if test -z $argv[1] 
	echo "Provide a directory"
else
	set chosen (
		for file in (fd . $argv[1] -t f -d 1)
			echo -en "$file\0icon\x1fthumbnail://$file\n"
		end | rofi -dmenu -p " " -show-icons -theme ~/.config/rofi/wallpapermenu.rasi)
	if test $chosen != $IMG
		~/.config/scripts/set_background (echo $chosen)
	end
end
