#!/usr/bin/fish

if test -z $argv[1] 
	echo "Provide a directory"
else
  set dir $argv[1]
	set chosen (
		for file in (find $dir -type f)
			if test -z $IMG; or test $file != $IMG
				echo -en "$file\0icon\x1fthumbnail://$file\n"
			end
		end | rofi -dmenu -p " " -show-icons -theme ~/.config/rofi/wallpapermenu.rasi)

	~/.config/scripts/set_background (echo $chosen)
end
